First

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -17,7 +17,7 @@ jobs:
       matrix:
         build:
           # Undeclared release tag finds latest from GitHub tags
-          - {latest: "true", kohya: "v24.1.6", python: "3.10", pytorch: "2.4.0", cuda: "12.1.1-base"}
+          - {latest: "true", fluxgym: "e118480", python: "3.10", pytorch: "2.5.1", cuda: "12.1.1-base"}
           
     steps:
       -
@@ -64,24 +64,24 @@ jobs:
           img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
           img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-cuda"
           
-          if [[ -z '${{ matrix.build.kohya }}' ]]; then
-                KOHYA_BUILD_REF="$(curl -s https://api.github.com/repos/bmaltais/kohya_ss/tags | jq -r '.[0].name')"
+          if [[ -z '${{ matrix.build.fluxgym }}' ]]; then
+                FLUXGYM_BUILD_REF="$(curl -s https://api.github.com/repos/cocktailpeanut/fluxgym/tags | jq -r '.[0].name')"
             else
-                KOHYA_BUILD_REF="${{ matrix.build.kohya }}"
+                FLUXGYM_BUILD_REF="${{ matrix.build.fluxgym }}"
             fi
-            [ -z "$KOHYA_BUILD_REF" ] && { echo "Error: KOHYA_BUILD_REF is empty. Exiting script." >&2; exit 1; }
-            echo "KOHYA_BUILD_REF=${KOHYA_BUILD_REF}" >> ${GITHUB_ENV}
+            [ -z "$FLUXGYM_BUILD_REF" ] && { echo "Error: FLUXGYM_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+            echo "FLUXGYM_BUILD_REF=${FLUXGYM_BUILD_REF}" >> ${GITHUB_ENV}
 
             base_tag="v2-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}"
 
             if [[ ${{ matrix.build.latest }} == "true" ]]; then
                 echo "Marking latest"
                 # GHCR.io
-                TAGS="${img_path_ghcr}:${base_tag}-${KOHYA_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest, ${img_path_ghcr}:latest-cuda"
+                TAGS="${img_path_ghcr}:${base_tag}-${FLUXGYM_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest, ${img_path_ghcr}:latest-cuda"
                 # Docker.io Tags
-                TAGS="${TAGS}, ${img_path_dhub}:${KOHYA_BUILD_REF}, ${img_path_dhub}:latest"
+                TAGS="${TAGS}, ${img_path_dhub}:${FLUXGYM_BUILD_REF}, ${img_path_dhub}:latest"
             else
-                TAGS="${img_path_ghcr}:${base_tag}-${KOHYA_BUILD_REF}, ${img_path_dhub}:${KOHYA_BUILD_REF}"
+                TAGS="${img_path_ghcr}:${base_tag}-${FLUXGYM_BUILD_REF}, ${img_path_dhub}:${FLUXGYM_BUILD_REF}"
             fi
           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
@@ -93,7 +93,7 @@ jobs:
             IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}
             PYTHON_VERSION=${{ matrix.build.python }}
             PYTORCH_VERSION=${{ matrix.build.pytorch }}
-            KOHYA_BUILD_REF=${{ env.KOHYA_BUILD_REF }}
+            FLUXGYM_BUILD_REF=${{ env.FLUXGYM_BUILD_REF }}
           push: true
           provenance: false
           tags: ${{ env.TAGS }}
@@ -104,7 +104,7 @@ jobs:
       fail-fast: false
       matrix:
         build:
-          - {latest: "true", kohya: "v24.1.6", python: "3.10", pytorch: "2.3.1", rocm: "6.0-core"}
+          - {latest: "true", fluxgym: "e118480", python: "3.10", pytorch: "2.3.1", rocm: "6.0-core"}
     steps:
       -
         name: Free Space
@@ -150,24 +150,24 @@ jobs:
           img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
           img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-rocm"
           
-          if [[ -z '${{ matrix.build.kohya }}' ]]; then
-                KOHYA_BUILD_REF="$(curl -s https://api.github.com/repos/bmaltais/kohya_ss/tags | jq -r '.[0].name')"
+          if [[ -z '${{ matrix.build.fluxgym }}' ]]; then
+                FLUXGYM_BUILD_REF="$(curl -s https://api.github.com/repos/cocktailpeanut/fluxgym/tags | jq -r '.[0].name')"
             else
-                KOHYA_BUILD_REF="${{ matrix.build.kohya }}"
+                FLUXGYM_BUILD_REF="${{ matrix.build.fluxgym }}"
             fi
-            [ -z "$KOHYA_BUILD_REF" ] && { echo "Error: KOHYA_BUILD_REF is empty. Exiting script." >&2; exit 1; }
-            echo "KOHYA_BUILD_REF=${KOHYA_BUILD_REF}" >> ${GITHUB_ENV}
+            [ -z "$FLUXGYM_BUILD_REF" ] && { echo "Error: FLUXGYM_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+            echo "FLUXGYM_BUILD_REF=${FLUXGYM_BUILD_REF}" >> ${GITHUB_ENV}
 
             base_tag="v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"
 
             if [[ ${{ matrix.build.latest }} == "true" ]]; then
                 echo "Marking latest"
                 # GHCR.io Tags
-                TAGS="${img_path_ghcr}:${base_tag}-${KOHYA_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
+                TAGS="${img_path_ghcr}:${base_tag}-${FLUXGYM_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
                 # Docker.io Tags
-                TAGS="${TAGS}, ${img_path_dhub}:${KOHYA_BUILD_REF}, ${img_path_dhub}:latest"
+                TAGS="${TAGS}, ${img_path_dhub}:${FLUXGYM_BUILD_REF}, ${img_path_dhub}:latest"
             else
-                TAGS="${img_path_ghcr}:${base_tag}-${KOHYA_BUILD_REF}, ${img_path_dhub}:${KOHYA_BUILD_REF}"
+                TAGS="${img_path_ghcr}:${base_tag}-${FLUXGYM_BUILD_REF}, ${img_path_dhub}:${FLUXGYM_BUILD_REF}"
             fi
           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
@@ -179,7 +179,7 @@ jobs:
             IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}
             PYTHON_VERSION=${{ matrix.build.python }}
             PYTORCH_VERSION=${{ matrix.build.pytorch }}
-            KOHYA_BUILD_REF=${{ env.KOHYA_BUILD_REF }}
+            FLUXGYM_BUILD_REF=${{ env.FLUXGYM_BUILD_REF }}
           push: true
           provenance: false
           tags: ${{ env.TAGS }}
